<?php $escape = $this->plugin('escapeHtml'); ?>
<?php if (count($filters) > 0): ?>
<div class="search-filters">
    <?php foreach ($filters as $filterLabel => $filterValues): ?>
    <div class="filter">
        <?php if(strpos($filterLabel, "AND") !== false){?>
            <span class="filter-label">and</span>
        <?php } ?> 
        <?php if(strpos($filterLabel, "OR") !== false){?>
            <span class="filter-label">or</span>
        <?php } ?>
        <!--<span class="filter-label"><?php echo $escape($filterLabel); ?></span>-->
        <?php foreach ($filterValues as $filterValue): ?>
        <span class="filter-value"><?php echo $escape($filterValue); ?></span>
        <?php endforeach; ?>
    </div>
    <?php endforeach; ?>
</div>
<?php endif; ?>
